name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Publish package to GitHub Packages
        run: npm publish --access public

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref }}
          release_name: Release v${{ github.ref }}
          draft: false
          prerelease: false

      - name: Comment on Issue
        uses: actions/github-script@v4
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = '${{ github.ref }}';
            const payload = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              body: `New release for tag ${tag}!`,
            };
            const response = await github.repos.createRelease(payload);
            console.log(response.data.html_url);
